# Step A- Data Pre-processing

## Step 1- Importing Libs

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Step 2- Import Dataset

In [2]:
dataset=pd.read_csv("Housing_Data.csv")

In [3]:
dataset

Income  House Age  Area Number of Rooms  Area Number of Bedrooms  \
0     79545.45857   5.682861              7.009188                     4.09   
1     79248.64245   6.002900              6.730821                     3.09   
2     61287.06718   5.865890              8.512727                     5.13   
3     63345.24005   7.188236              5.586729                     3.26   
4     59982.19723   5.040555              7.839388                     4.23   
...           ...        ...                   ...                      ...   
4995  60567.94414   7.830362              6.137356                     3.46   
4996  78491.27543   6.999135              6.576763                     4.02   
4997  63390.68689   7.250591              4.805081                     2.13   
4998  68001.33124   5.534388              7.130144                     5.44   
4999  65510.58180   5.992305              6.792336                     4.07   

      Area Population         Price  
0         23086.80050  1.059034e+06  
1         40173.07217  1.505891e+06  
2         36882.15940  1.058988e+06  
3         34310.24283  1.260617e+06  
4         26354.10947  6.309435e+05  
...               ...           ...  
4995      22837.36103  1.060194e+06  
4996      25616.11549  1.482618e+06  
4997      33266.14549  1.030730e+06  
4998      42625.62016  1.198657e+06  
4999      46501.28380  1.298950e+06  

[5000 rows x 6 columns]

In [4]:
dataset.head()

Income  House Age  Area Number of Rooms  Area Number of Bedrooms  \
0  79545.45857   5.682861              7.009188                     4.09   
1  79248.64245   6.002900              6.730821                     3.09   
2  61287.06718   5.865890              8.512727                     5.13   
3  63345.24005   7.188236              5.586729                     3.26   
4  59982.19723   5.040555              7.839388                     4.23   

   Area Population         Price  
0      23086.80050  1.059034e+06  
1      40173.07217  1.505891e+06  
2      36882.15940  1.058988e+06  
3      34310.24283  1.260617e+06  
4      26354.10947  6.309435e+05

## Step 3- To create Feature matrix(X) and Dependent variable vector(Y)

In [5]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [6]:
x

array([[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,
        2.30868005e+04],
       [7.92486424e+04, 6.00289981e+00, 6.73082102e+00, 3.09000000e+00,
        4.01730722e+04],
       [6.12870672e+04, 5.86588984e+00, 8.51272743e+00, 5.13000000e+00,
        3.68821594e+04],
       ...,
       [6.33906869e+04, 7.25059062e+00, 4.80508098e+00, 2.13000000e+00,
        3.32661455e+04],
       [6.80013312e+04, 5.53438842e+00, 7.13014386e+00, 5.44000000e+00,
        4.26256202e+04],
       [6.55105818e+04, 5.99230531e+00, 6.79233610e+00, 4.07000000e+00,
        4.65012838e+04]])

In [7]:
y

array([1059033.558, 1505890.915, 1058987.988, ..., 1030729.583,
       1198656.872, 1298950.48 ])

## Step 4- Replace missing values 

In [8]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,:])
x[:,:]=imputer.transform(x[:,:])

## Step 5- Encoding (Not Required)

## Step 6- Splitting dataset into training and testing dataset

In [9]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

## Step 7- Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain[:,:]=sc.fit_transform(xtrain[:, :])
xtest[:,:]=sc.fit_transform(xtest[:, :])

# Step B- Building my Linear Regression model

## Step 1- Training the model 

In [11]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()             
LR.fit(xtrain,ytrain)

LinearRegression()

## Step 2- Testing the linear model

In [12]:
yestimate=LR.predict(xtest)

In [13]:
xtest

array([[ 0.60333895,  0.79088606, -0.36530619,  0.1048297 ,  0.66381728],
       [ 0.71173495,  0.18954984,  0.17895429, -0.52863144,  0.88562112],
       [-0.07845365, -0.16133912, -1.8506246 ,  0.15355748, -0.09171046],
       ...,
       [ 2.97702267, -0.10311435, -0.32605408,  0.29161952, -1.02821984],
       [-0.52350157, -0.0824624 , -0.4841566 , -0.74790644, -0.16282439],
       [-2.73121681,  1.01874286,  1.92344757,  0.20228525, -1.08946656]])

In [14]:
ytest

array([1413579.817  , 1618721.138  ,  841392.493  ,  881443.9247 ,
       1174747.551  ,  266298.8811 , 1877941.971  , 1022408.901  ,
       1766248.403  ,  949072.2496 ,  565937.2006 , 1437153.959  ,
       1582605.535  , 1009854.705  , 1116351.753  , 1255736.409  ,
       1504441.01   ,  837540.1697 , 1096069.287  , 1205962.995  ,
       1130844.029  , 1815920.45   , 1023595.113  , 1054304.172  ,
       1399909.049  , 1710612.03   ,  670063.0223 , 1245785.051  ,
       1168760.428  ,  412269.2034 ,  677988.2555 , 1715435.991  ,
        662630.3439 , 1167449.99   ,  714706.4289 , 1411217.493  ,
       1200125.447  , 1322439.108  , 1127637.557  , 1066040.789  ,
       1383842.185  , 1364306.769  , 1682105.847  , 1380602.556  ,
        880084.7004 ,  779207.5546 , 1029861.623  , 1106149.686  ,
       1327806.729  , 1377939.775  , 1584317.753  ,  944288.911  ,
        759799.8758 , 1028493.601  , 1164497.019  , 1383508.062  ,
       1696339.544  ,  930011.5709 , 1092649.709  , 1686562.16

In [17]:
LR.coef_

array([229898.66280911, 164210.49487762, 120661.8149709 ,   1904.50903449,
       150262.88567152])

In [18]:
LR.intercept_

1233641.8667294497

In [19]:
xtest

array([[ 0.60333895,  0.79088606, -0.36530619,  0.1048297 ,  0.66381728],
       [ 0.71173495,  0.18954984,  0.17895429, -0.52863144,  0.88562112],
       [-0.07845365, -0.16133912, -1.8506246 ,  0.15355748, -0.09171046],
       ...,
       [ 2.97702267, -0.10311435, -0.32605408,  0.29161952, -1.02821984],
       [-0.52350157, -0.0824624 , -0.4841566 , -0.74790644, -0.16282439],
       [-2.73121681,  1.01874286,  1.92344757,  0.20228525, -1.08946656]])

In [22]:
LR.predict([[80000,7,6,4,5000]])

array([1.91463222e+10])